# Generated by Django 4.2 on 2023-05-30 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Won", "Won"),
                            ("Pending", "Pending"),
                            ("Lost", "Lost"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("3D", "3D"),
                            ("2D", "2D"),
                            ("OBN", "OBN"),
                            ("WAZ", "WAZ"),
                            ("2D Repro", "2D Repro"),
                            ("3D Repro", "3D Repro"),
                            ("OBN Repro", "OBN Repro"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MC", "MC"),
                            ("Converted Contract", "Converted Contract"),
                            ("Proprietary", "Proprietary"),
                        ],
                        default="MC",
                        max_length=20,
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
