# Generated by Django 4.2 on 2023-05-31 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projectdb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Permit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permit_name", models.CharField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "regulatory_agency",
                    models.CharField(
                        choices=[
                            ("ANP", "ANP"),
                            ("IBAMA", "IBAMA"),
                            ("DNPM", "DNPM"),
                            ("MMA", "MMA"),
                            ("MME", "MME"),
                            ("ANH", "ANH"),
                            ("ANLA", "ANLA"),
                            ("SNE_ARG", "SNE_ARG"),
                            ("SNE_BOL", "SNE_BOL"),
                            ("ANCAP", "ANCAP"),
                            ("CNH", "CNH"),
                            ("Staatsolie", "Staatsolie"),
                            ("MEEI", "Ministry of Energy and Energy Industries (MEEI)"),
                            ("MEB", "Ministry of Energy and Business (MEB)"),
                            ("MSET", "Jamaica (MSET)"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                (
                    "permit_status",
                    models.CharField(
                        choices=[
                            ("In Application", "In Application"),
                            ("Not Started", "Not Started"),
                            ("Denied", "Denied"),
                            ("Cancelled", "Cancelled"),
                            ("Valid", "Valid"),
                        ],
                        default="Not Started",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateField()),
                ("granted_on", models.DateField(blank=True, default=None, null=True)),
                (
                    "validity_period",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("expiry_date", models.DateField(editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="permit",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projectdb.permit",
            ),
        ),
    ]
